# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-16 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EngineCapacities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_capacity', models.FloatField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EngineTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_type', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
